import { Award, BarChart3, BookOpen, CalendarCheck, ClipboardCheck, CircleCheck, GraduationCap, Presentation, School, Users, Video } from 'lucide-react';

const icons = { users: Users, material: BookOpen, test: ClipboardCheck };

export function DashboardOverview({ role }: { role: 'admin' | 'dosen' | 'mahasiswa' }) {
  const stats = role === 'admin'
    ? [{ label: 'Pengguna aktif', value: '24', color: 'border-l-indigo-500', text: 'text-indigo-500', icon: Users }, { label: 'Materi tersedia', value: '12', color: 'border-l-emerald-500', text: 'text-emerald-500', icon: BookOpen }, { label: 'Test berjalan', value: '6', color: 'border-l-cyan-500', text: 'text-cyan-600', icon: ClipboardCheck }, { label: 'Kelas terdaftar', value: '8', color: 'border-l-amber-400', text: 'text-amber-500', icon: GraduationCap }]
    : role === 'dosen'
      ? [{ label: 'Materi dibuat', value: '12', color: 'border-l-indigo-500', text: 'text-indigo-500', icon: Video }, { label: 'Kelas aktif', value: '8', color: 'border-l-emerald-500', text: 'text-emerald-500', icon: School }, { label: 'Test dijadwalkan', value: '6', color: 'border-l-cyan-500', text: 'text-cyan-600', icon: CalendarCheck }, { label: 'Mahasiswa', value: '24', color: 'border-l-amber-400', text: 'text-amber-500', icon: Users }]
      : [{ label: 'Materi tersedia', value: '12', color: 'border-l-indigo-500', text: 'text-indigo-500', icon: BookOpen }, { label: 'Materi selesai', value: '8', color: 'border-l-emerald-500', text: 'text-emerald-500', icon: CircleCheck }, { label: 'Test tersedia', value: '6', color: 'border-l-cyan-500', text: 'text-cyan-600', icon: Presentation }, { label: 'Rata-rata nilai', value: '88', color: 'border-l-amber-400', text: 'text-amber-500', icon: Award }];
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-indigo-500">Portal {role}</p><h1 className="mt-1 text-3xl font-bold text-slate-800">Dashboard</h1><p className="mt-2 text-slate-500">Ringkasan aktivitas pembelajaran Anda.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((style) => { const Icon = style.icon; return <div key={style.label} className={`relative overflow-hidden rounded-xl border border-slate-200 border-l-4 ${style.color} bg-white p-5 shadow-sm transition-transform hover:-translate-y-0.5 hover:shadow-md`}><Icon className="absolute right-5 top-1/2 size-9 -translate-y-1/2 text-slate-100" strokeWidth={1.8} /><p className={`text-xs font-bold uppercase ${style.text}`}>{style.label}</p><p className="mt-1 text-2xl font-bold text-slate-700">{style.value}</p><p className="mt-2 text-xs font-medium text-slate-400">Data tampilan</p></div>; })}</div><div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-800">Aktivitas pembelajaran</h2><p className="text-sm text-slate-500">Visualisasi sementara</p></div><BarChart3 className="size-5 text-indigo-500" /></div><div className="mt-8 flex h-48 items-end gap-3 border-b border-slate-100 px-2">{[35, 58, 42, 70, 55, 84, 63, 92].map((height, index) => <div key={index} className="flex-1 rounded-t bg-gradient-to-t from-indigo-600 to-indigo-300" style={{ height: `${height}%` }} />)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-800">Informasi</h2><div className="mt-5 space-y-4"><p className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-700">Menu pada sidebar telah siap sebagai tampilan.</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-600">Fitur data dan pengaturan akan dihubungkan pada tahap berikutnya.</p></div></section></div></div>;
}

export function PlaceholderPage({ title, description, type }: { title: string; description: string; type: keyof typeof icons }) {
  const Icon = icons[type];
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-indigo-500">Segera hadir</p><h1 className="mt-1 text-3xl font-bold text-slate-800">{title}</h1><p className="mt-2 text-slate-500">{description}</p></div><section className="flex min-h-80 flex-col items-center justify-center rounded-xl border border-dashed border-indigo-200 bg-white p-8 text-center shadow-sm"><div className="flex size-16 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-600"><Icon className="size-8" /></div><h2 className="mt-5 text-xl font-bold">Tampilan {title}</h2><p className="mt-2 max-w-md text-sm text-slate-500">Halaman ini sudah tersedia sebagai rancangan antarmuka. Fitur pengelolaan data akan ditambahkan pada tahap berikutnya.</p></section></div>;
}
